name:        rio-prettyprint
version:     0.1.7.0
synopsis:    Pretty-printing for RIO
description: Combine RIO's log capabilities with pretty printing
category:    Development
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2018-2023 FP Complete
license:     BSD3
github:      commercialhaskell/rio-prettyprint
extra-source-files:
- ChangeLog.md
- README.md
- stack.yaml

dependencies:
- base >=4.10 && < 5
- Cabal
- aeson
- annotated-wl-pprint
- ansi-terminal >= 0.9
- array
- colour
- mtl
- path > 0.9.1
- rio
- text

library:
  source-dirs: src/
