name:        rio-prettyprint
version:     0.1.0.0
synopsis:    Pretty-printing for RIO
category:    Development
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2018-2019 FP Complete
license:     BSD3
github:      commercialhaskell/stack # TODO move to commercialhaskell/rio-prettyprint!

dependencies:
- base >=4.10 && < 5
- Cabal
- aeson
- annotated-wl-pprint
- ansi-terminal
- array
- colour
- mtl
- path
- rio
- text

library:
  source-dirs: src/
