name:        rio-prettyprint
version:     0.1.2.0
synopsis:    Pretty-printing for RIO
category:    Development
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2018-2019 FP Complete
license:     BSD3
github:      commercialhaskell/rio-prettyprint
description: Combine RIO's log capabilities with pretty printing

dependencies:
- base >=4.10 && < 5
- Cabal
- aeson
- annotated-wl-pprint
- ansi-terminal >= 0.9
- array
- colour
- mtl
- path
- rio
- text

library:
  source-dirs: src/
