jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-def:
        BUILD: stack
      stack-ghc-8.4.4:
        BUILD: stack
        ARGS: "--stack-yaml stack-ghc-8.4.4.yaml"
      stack-ghc-8.6.5:
        BUILD: stack
        ARGS: "--stack-yaml stack-ghc-8.6.5.yaml"
      stack-nightly:
        BUILD: stack
        ARGS: "--resolver nightly"
    maxParallel: 6
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-i386 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack --install-ghc $ARGS test --bench --only-dependencies
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
