name: Tests

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        resolver:
        - nightly-2023-08-29 # GHC 9.6.2
        - lts-21.9 # GHC 9.4.6
        - lts-20.26 # GHC 9.2.8
        - lts-19.33 # GHC 9.0.2
    steps:
    - name: Clone project
      uses: actions/checkout@v3
    - name: Build and run tests
      shell: bash
      run: |
        set -ex
        stack --version
        stack --resolver=${{ matrix.resolver }} build --fast --haddock --no-haddock-deps
