name: Tests

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        snapshot:
        - stack-ghc-9.12.4.yaml
        - stack-ghc-9.10.3.yaml
        - stack-ghc-9.8.4.yaml
        - stack-ghc-9.6.7.yaml
    steps:
    - name: Clone project
      uses: actions/checkout@v6
    - name: Build and run tests
      shell: bash
      run: |
        set -ex

        if [[ "${{ matrix.os }}" == "macos-latest" ]]
        then
          # As at 2026-04-17:
          #
          # * macos-latest does not include Haskell tools.
          curl -sSL https://get.haskellstack.org/ | sh
        fi

        stack --version
        stack --snapshot=${{ matrix.snapshot }} build --fast --haddock --no-haddock-deps
